import type { FormEvent } from "react";
import type { AgentAccessMode, AgentActionLogItem, AudioDevicesResponse, HealthResponse, LLMOptionsResponse, LiveSnapshot, UserProfilePayload } from "../../lib/types";
import type { ReminderNotificationPermission } from "../../lib/notifications";
import type { ConnectionState, RemoteVoiceDiagnostics } from "../../lib/runtime";
import type { InspectorSection } from "../../lib/ui";

export type SettingsOverlayProps = {
  isOpen: boolean;
  onClose: () => void;
  apiBaseUrl: string;
  apiBaseUrlDraft: string;
  onApiBaseUrlDraftChange: (value: string) => void;
  onSaveApiBaseUrl: () => void;
  onClearApiBaseUrl: () => void;
  apiBaseUrlStatus: string;
  currentListenerStatus: string;
  currentModel: string;
  currentBackend: string;
  agentAccessMode: AgentAccessMode;
  onAgentAccessModeChange: (value: AgentAccessMode) => void;
  activeInspectorSection: InspectorSection;
  onSectionChange: (section: InspectorSection) => void;
  onRefreshWorkspace: () => void;
  onReconnectHost: () => void;
  onRefreshAgentActionLog: () => void;
  llmOptions: LLMOptionsResponse | null;
  selectedBackend: string;
  selectedModel: string;
  onSelectedBackendChange: (value: string) => void;
  onSelectedModelChange: (value: string) => void;
  onRefreshLlmSettings: () => void;
  onApplyLlmSettings: () => void;
  llmStatus: string;
  audioDevices: AudioDevicesResponse | null;
  selectedDeviceIndex: number | "";
  onSelectAudioDevice: (index: number) => void;
  onListenerAction: (action: "start" | "stop" | "shutdown") => void;
  isListening: boolean;
  deviceStatus: string;
  remoteVoiceAvailable: boolean;
  remoteVoiceDisabledReason: string;
  remoteVoiceStatus: string;
  isRemoteRecording: boolean;
  isRemoteTranscribing: boolean;
  remoteRecordingElapsedLabel: string;
  remoteVoicePressToTalk: boolean;
  onToggleRemoteVoice: () => void;
  speakRepliesOnThisDevice: boolean;
  onToggleSpeakRepliesOnThisDevice: () => void;
  replyAudioStatus: string;
  latestReplyAudioReady: boolean;
  isReplyAudioPlaying: boolean;
  onPlayLatestReplyAudio: () => void;
  connectionState: ConnectionState;
  connectionSummary: string;
  agentActionLog: AgentActionLogItem[];
  agentActionLogStatus: string;
  lastConnectionError: string;
  lastSuccessfulContactLabel: string;
  lastRoundTripMs: number | null;
  isClientOnline: boolean;
  health: HealthResponse | null;
  remoteVoiceDiagnostics: RemoteVoiceDiagnostics;
  notificationsSupported: boolean;
  notificationsEnabled: boolean;
  notificationPermission: ReminderNotificationPermission;
  notificationNeedsSystemSettings: boolean;
  notificationStatus: string;
  notificationSyncing: boolean;
  scheduledReminderCount: number;
  lastNotificationSyncLabel: string;
  onSetNotificationsEnabled: (value: boolean) => void;
  onRequestNotificationsPermission: () => void;
  onSyncNotifications: () => void;
  onSendTestNotification: () => void;
  profile: UserProfilePayload;
  onProfileChange: (updater: (current: UserProfilePayload) => UserProfilePayload) => void;
  onSaveProfile: (event: FormEvent<HTMLFormElement>) => void;
  profileStatus: string;
  live: LiveSnapshot | null;
};
